module.exports = {
    NOTIFY_ADMIN_MSG: '\nYou have new request\nPlease check and confirm\nRequestor: @requestor,\nTelephone: @telephone,\nDescription: @description,\nMap: @location',
    NOTIFY_VOLUNTEER_MSG: '\nRequestor: @requestor,\nTelephone: @telephone,\nDescription: @description,\nStatus: @status,\nHelpBy: @helpBy,\nMap: @location',
    SEND_LINE_NOTIFY_COMPLETED: 'Send LINE notify completed.',
    SEND_SOS_COMPLETED: 'SOS send complete, please waiting rescue team few minutes.',
    DEL_TASK_COMPLETED: 'Task has been deleted.',
    UPD_TASK_COMPLETED: 'Task @taskId has been updated.',
    USER_CLT_DUP_INDEX: 'Username already exists',
    USER_CLT_REQ_USERNAME: 'Username is required',
    USER_CLT_REQ_FIRSTNAME: 'Firstname is required',
    USER_CLT_EMAIL_NOT_VALID: 'This e-mail address is not valid',
    USER_CLT_PWD_ATLEAST: 'Password must be at least 8 characters',
    USER_CLT_REQ_PROVIDER: 'Provider is required',
    USER_CLT_DF_PRIVILEGES: 'User',
    TASK_CLT_DUP_INDEX: 'Duplicate data, please send again.',
    TASK_CLT_REQ_TASKID: 'taskId is required',
    TASK_CLT_DF_STATUS: 'Waiting for help',
    TASK_CLT_DF_REQUESTOR: 'Guest',
    TASK_IS_NOT_UP_IMG_YET: 'Task @taskId is not uploaded image yet',
    DB_ERR: 'Something went wrong.',
    SOMETHING_ERR: 'Something went wrong.',
    DIR_HAS_BEEN_CREATED: 'Directory has been recursively created.',
    FILE_HAS_BEEN_UPLOAD: 'File have been uploaded.',
    PAGE_NOT_FOUND: 'We\'re sorry, the page you\'ve requested cannot be found.',
    ARR_CONSTRUCTOR: [].constructor,
    OBJ_CONSTRUCTOR: {}.constructor
};